### ISSUE TITLE
Plain text password in logins.js file

### ISSUE THREAD

**Issue by shellmage** [TEAMVV/B#1]
I noticed you uploaded the login.js file with your credentials, it's mentioned in the [facebook-chat-api](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#password-safety) that you should delete them from the login.js file after generating the appstate.json file, and also you shouldn't upload the appstate.json file to github because it can be used to login to your account.
Also, you should give credit to the original developers of open-source software and not just copy-paste code and upload it to github as your own.

**Comment by BotolMehedi** [comment]
@shellmage I change the original title for some reason, I already share your BOT link in my Facebook public group & my Telegram Group also My messenger group. But i change real credit for other reason. Don't Mind & sorryyy.
